### ISSUE TITLE
Introduce flows tied to Tendrl objects

### ISSUE THREAD

**Issue by nnDarshan** [Tendrl/gluster_integration#90] opened 2016-12-13 08:52 UTC
All the actions that are specific to an object should be defined as flows under that particular object. Currently such flows are defined at global level. For example, the start volume, stop volume, delete volume flows should be under volume object.
Specification PR: https://github.com/Tendrl/specifications/pull/10
Specification issue: https://github.com/Tendrl/specifications/issues/34

**Comment by shtripat** [comment] 2016-12-30 09:12
Closing as its duplicate of https://github.com/Tendrl/gluster_integration/issues/95

**Closed by shtripat** 2016-12-30 09:12 UTC
